language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

matrix:
  include:
    - python: "2.7"
    #- python: "pypy"
    #- python: "3.4"
    #- python: "3.5"
    #- python: "pypy3"
    #- python: "3.5"

install:
    - printenv
    - gcc --version
    - pip install ply
    - pip install ordereddict
    - pip install pyutilib
    - python setup.py develop

script:
    - nosetests -v
