language: python

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5

matrix:
  include:
  - python: '2.7'
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5 COVERAGE_OPTS='--cov=gcovr --cov-branch'
  - python: pypy
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
  - python: '3.4'
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
  - python: '3.5'
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5 COVERAGE_OPTS='--cov=gcovr --cov-branch'
  - python: pypy3.5-5.8.0
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5

install:
- printenv
- $CXX --version
- pip install pytest pytest-cov
- pip install ply
- pip install ordereddict
- pip install pyutilib
- pip install flake8
- pip install coverage
- pip install codecov
- python setup.py develop

script:
- flake8 --ignore=E501
- python -m pytest -v $COVERAGE_OPTS gcovr doc/examples
- if [ -n "$COVERAGE_OPTS" ]; then codecov -X gcov search; fi

deploy:
    # disable testpypi deployment until #197 is fixed
    # - provider: pypi
    # - server: https://test.pypi.org/legacy/
    # - user: whart111
    # - password:
    # -   secure: "TpOWxwD/izvCyz585nvwIq4plfbgi8BKqUW5Xm8uJRWEZ6g1/1K2Om7jxY2sP2XunzrlV85Nnl0juFKzVGfQEXo5yFGpUqx1r74cfFMd3mMATh5VndZuyrR8ZWB70mt/AGEFCPCFt82UqW2gbbZcO8T1i++5vl9hhTUlcaLo9vM="
    # - distributions: sdist --format=gztar bdist_wheel
    # - on:
    # -   tags: false
    # -   branch: master
    # -   python: '2.7'
  - provider: pypi
    user: whart111
    password:
      secure: "TpOWxwD/izvCyz585nvwIq4plfbgi8BKqUW5Xm8uJRWEZ6g1/1K2Om7jxY2sP2XunzrlV85Nnl0juFKzVGfQEXo5yFGpUqx1r74cfFMd3mMATh5VndZuyrR8ZWB70mt/AGEFCPCFt82UqW2gbbZcO8T1i++5vl9hhTUlcaLo9vM="
    distributions: sdist --format=gztar bdist_wheel
    on:
      tags: true
      branch: master
      python: '2.7'

