language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

matrix:
  include:
    - python: "2.7"
      env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
    - python: "pypy"
      env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
    - python: "3.4"
      env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
    - python: "3.5"
      env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
    - python: "pypy3"
      env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5

install:
    - printenv
    - $CXX --version
    - pip install ply
    - pip install ordereddict
    - pip install pyutilib
    - python setup.py develop

script:
    - nosetests -v
